package com.jpmorgan.debugger;

/**
 * This class is a runtime exception generated by the debugger.
 */
public class DebuggerRuntimeException extends RuntimeException {
    /** Serial Version UID */
    private static final long serialVersionUID = -4580097618290046297L;

    public DebuggerRuntimeException() {
        super();
    }

    public DebuggerRuntimeException(String message) {
        super(message);
    }

    public DebuggerRuntimeException(Throwable cause) {
        super(cause);
    }

    public DebuggerRuntimeException(String message, Throwable cause) {
        super(message, cause);
    }

}
