/**
 *
 * @author  ffleurey
 */

package com.jpmorgan.tracer;

public class OptionsDialog extends javax.swing.JDialog {
    
    /** Creates new form OptionsDialog */
    public OptionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bindAll();
    }

    protected void bindAll() {
        TraceProvider tracer = TraceProvider.getInstance();
        this.tb_thread_name.setText(tracer.getThreadToTrace());
        if (tracer.isExclusionMode()) {
            this.list_classes.setListData(tracer.getExcludes());
            this.t_expect.setSelected(true);
            this.t_include.setSelected(false);
        }
        else {
            this.list_classes.setListData(tracer.getIncludes());
            this.t_expect.setSelected(false);
            this.t_include.setSelected(true);
        }
        this.tr_check.setSelected(tracer.getStepTrace());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        b_cancel = new javax.swing.JButton();
        b_ok = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        t_include = new javax.swing.JRadioButton();
        t_expect = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        list_classes = new javax.swing.JList();
        jPanel9 = new javax.swing.JPanel();
        b_rm = new javax.swing.JButton();
        b_add = new javax.swing.JButton();
        tb_toadd = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        tr_check = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tb_thread_name = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();

        setTitle("Choose classes to trace :");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        b_cancel.setText("Cancel");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        jPanel1.add(b_cancel, java.awt.BorderLayout.WEST);

        b_ok.setText("OK");
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        jPanel1.add(b_ok, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Classes to trace : "));
        t_include.setText("Only trace listed classes.");
        buttonGroup1.add(t_include);
        t_include.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_includeActionPerformed(evt);
            }
        });

        jPanel3.add(t_include);

        t_expect.setSelected(true);
        t_expect.setText("Trace all classes except listed ones.");
        buttonGroup1.add(t_expect);
        t_expect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_expectActionPerformed(evt);
            }
        });

        jPanel3.add(t_expect);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel4.add(list_classes, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.BorderLayout());

        b_rm.setText("Remove");
        b_rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rmActionPerformed(evt);
            }
        });

        jPanel9.add(b_rm, java.awt.BorderLayout.WEST);

        b_add.setText("Add");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        jPanel9.add(b_add, java.awt.BorderLayout.EAST);

        tb_toadd.setText("<YourClass>");
        tb_toadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_toaddActionPerformed(evt);
            }
        });

        jPanel9.add(tb_toadd, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel9, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel4);

        jPanel5.add(jPanel3);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(new javax.swing.border.TitledBorder("Options : "));
        tr_check.setSelected(true);
        tr_check.setText("Step Trace");
        tr_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_checkActionPerformed(evt);
            }
        });

        jPanel6.add(tr_check, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Name of thread to trace :");
        jPanel7.add(jLabel1);

        tb_thread_name.setText("main");
        jPanel7.add(tb_thread_name);

        jPanel7.add(jPanel8);

        jPanel6.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel5.add(jPanel6);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void tb_toaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_toaddActionPerformed
        // Add your handling code here:
         TraceProvider tp = TraceProvider.getInstance();
        if (tp.isExclusionMode()) {
            java.util.Vector v = tp.getExcludes();
            v.add(tb_toadd.getText());
            tp.setExcludes(v);
        }
        else {
            java.util.Vector v = tp.getIncludes();
            v.add(tb_toadd.getText());
            tp.setIncludes(v);
        }
        bindAll();
    }//GEN-LAST:event_tb_toaddActionPerformed

    private void b_rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rmActionPerformed
        // Add your handling code here:
        TraceProvider tp = TraceProvider.getInstance();
        try {
            if (tp.isExclusionMode()) {
                java.util.Vector v = tp.getExcludes();
                v.remove(list_classes.getSelectedValue());
                tp.setExcludes(v);
            }
            else {
                java.util.Vector v = tp.getIncludes();
                v.remove(list_classes.getSelectedValue());
                tp.setIncludes(v);
            }
        } catch (Exception e) { e.printStackTrace(); }
        bindAll();
    }//GEN-LAST:event_b_rmActionPerformed

    private void tr_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_checkActionPerformed
        // Add your handling code here:
        TraceProvider.getInstance().setStepTrace(tr_check.isSelected());
        bindAll();
    }//GEN-LAST:event_tr_checkActionPerformed

    private void t_expectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_expectActionPerformed
        // Add your handling code here:
        TraceProvider.getInstance().setExclusionMode(true);
        bindAll();
    }//GEN-LAST:event_t_expectActionPerformed

    private void t_includeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_includeActionPerformed
        // Add your handling code here:
        TraceProvider.getInstance().setExclusionMode(false);
        bindAll();
    }//GEN-LAST:event_t_includeActionPerformed

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        
        TraceProvider tp = TraceProvider.getInstance();
        if (tp.isExclusionMode()) {
            java.util.Vector v = tp.getExcludes();
            v.add(tb_toadd.getText());
            tp.setExcludes(v);
        }
        else {
            java.util.Vector v = tp.getIncludes();
            v.add(tb_toadd.getText());
            tp.setIncludes(v);
        }
        bindAll();
    }//GEN-LAST:event_b_addActionPerformed

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_b_cancelActionPerformed

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        // Add your handling code here:
        TraceProvider tp = TraceProvider.getInstance();
        tp.setThreadToTrace(tb_thread_name.getText());
        this.dispose();
        
    }//GEN-LAST:event_b_okActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new OptionsDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton b_rm;
    private javax.swing.JButton b_cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tb_toadd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton t_include;
    private javax.swing.JButton b_ok;
    private javax.swing.JTextField tb_thread_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox tr_check;
    private javax.swing.JList list_classes;
    private javax.swing.JButton b_add;
    private javax.swing.JRadioButton t_expect;
    // End of variables declaration//GEN-END:variables

}
